/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author sanfra
 */
public class JF_Productos extends javax.swing.JFrame {

    public JF_Productos(){
        initComponents();
    }
    
    public JButton getjB_Actualizar() {
        return jB_Actualizar;
    }

    public void setjB_Actualizar(JButton jB_Actualizar) {
        this.jB_Actualizar = jB_Actualizar;
    }

    public JButton getjB_Eliminar() {
        return jB_Eliminar;
    }

    public void setjB_Eliminar(JButton jB_Eliminar) {
        this.jB_Eliminar = jB_Eliminar;
    }

    public JButton getjB_Insertar() {
        return jB_Insertar;
    }

    public void setjB_Insertar(JButton jB_Insertar) {
        this.jB_Insertar = jB_Insertar;
    }

    public JButton getjB_Limpiar() {
        return jB_Limpiar;
    }

    public void setjB_Limpiar(JButton jB_Limpiar) {
        this.jB_Limpiar = jB_Limpiar;
    }

    public JButton getjB_MostrarTodos() {
        return jB_MostrarTodos;
    }

    public void setjB_MostrarTodos(JButton jB_MostrarTodos) {
        this.jB_MostrarTodos = jB_MostrarTodos;
    }

    public JComboBox<String> getjC_Linea() {                                    //COMBO BOX
        return jC_Linea;
    }

    public void setjC_Linea(JComboBox<String> jC_Linea) {
        this.jC_Linea = jC_Linea;
    }

    public JLabel getjLbl_Codigo() {
        return jLbl_Codigo;
    }

    public void setjLbl_Codigo(JLabel jLbl_Codigo) {
        this.jLbl_Codigo = jLbl_Codigo;
    }

    public JLabel getjLbl_Descripcion() {
        return jLbl_Descripcion;
    }

    public void setjLbl_Descripcion(JLabel jLbl_Descripcion) {
        this.jLbl_Descripcion = jLbl_Descripcion;
    }

    public JLabel getjLbl_Linea() {
        return jLbl_Linea;
    }

    public void setjLbl_Linea(JLabel jLbl_Linea) {
        this.jLbl_Linea = jLbl_Linea;
    }

    public JLabel getjLbl_Marca() {
        return jLbl_Marca;
    }

    public void setjLbl_Marca(JLabel jLbl_Marca) {
        this.jLbl_Marca = jLbl_Marca;
    }

    public JLabel getjLbl_Stock() {
        return jLbl_Stock;
    }

    public void setjLbl_Stock(JLabel jLbl_Stock) {
        this.jLbl_Stock = jLbl_Stock;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjT_Productos() {
        return jT_Productos;
    }

    public void setjT_Productos(JTable jT_Productos) {
        this.jT_Productos = jT_Productos;
    }

    public JTextField getjTxt_Codigo() {
        return jTxt_Codigo;
    }

    public void setjTxt_Codigo (String jTxt_Codigo) {
        this.jTxt_Codigo.setText(jTxt_Codigo);
    }

    public JTextField getjTxt_Descripcion() {
        return jTxt_Descripcion;
    }

    public void setjTxt_Descripcion(String jTxt_Descripcion) {
        this.jTxt_Descripcion.setText(jTxt_Descripcion);
    }

    public JTextField getjTxt_Marca() {
        return jTxt_Marca;
    }

    public void setjTxt_Marca(String jTxt_Marca) {
        this.jTxt_Marca.setText(jTxt_Marca);
    }

    public JTextField getjTxt_Stock() {
        return jTxt_Stock;
    }


    public void setjTxt_Stock(String jTxt_Stock) {
        this.jTxt_Stock.setText(jTxt_Stock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Productos = new javax.swing.JTable();
        jLbl_Codigo = new javax.swing.JLabel();
        jLbl_Linea = new javax.swing.JLabel();
        jLbl_Marca = new javax.swing.JLabel();
        jLbl_Descripcion = new javax.swing.JLabel();
        jLbl_Stock = new javax.swing.JLabel();
        jTxt_Codigo = new javax.swing.JTextField();
        jTxt_Marca = new javax.swing.JTextField();
        jTxt_Stock = new javax.swing.JTextField();
        jTxt_Descripcion = new javax.swing.JTextField();
        jB_Insertar = new javax.swing.JButton();
        jB_Actualizar = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();
        jB_Limpiar = new javax.swing.JButton();
        jB_MostrarTodos = new javax.swing.JButton();
        jC_Linea = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(32, 32));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(600, 600));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 600));

        jT_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Línea", "Marca", "Descripción", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_Productos);

        jLbl_Codigo.setText("Codigo");

        jLbl_Linea.setText("Linea");

        jLbl_Marca.setText("Marca");

        jLbl_Descripcion.setText("Descripción");

        jLbl_Stock.setText("Stock");

        jTxt_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_CodigoActionPerformed(evt);
            }
        });

        jB_Insertar.setText("Insertar");
        jB_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_InsertarActionPerformed(evt);
            }
        });

        jB_Actualizar.setText("Actualizar");

        jB_Eliminar.setText("Eliminar");

        jB_Limpiar.setText("Limpiar");

        jB_MostrarTodos.setText("Mostrar Todos");

        jC_Linea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lámparas", "Inducidos", "Baterías", "LED" }));
        jC_Linea.setToolTipText("");
        jC_Linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_LineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_Codigo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLbl_Descripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTxt_Descripcion))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLbl_Marca)
                                        .addComponent(jLbl_Stock))
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTxt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(56, 56, 56)
                                            .addComponent(jLbl_Linea)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jC_Linea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jTxt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jB_Insertar)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jB_MostrarTodos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Codigo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLbl_Linea)
                        .addComponent(jC_Linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Marca)
                    .addComponent(jTxt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Stock)
                    .addComponent(jTxt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Descripcion)
                    .addComponent(jTxt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Insertar)
                    .addComponent(jB_Actualizar)
                    .addComponent(jB_Eliminar)
                    .addComponent(jB_Limpiar)
                    .addComponent(jB_MostrarTodos))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_CodigoActionPerformed

    private void jB_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_InsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_InsertarActionPerformed

    private void jC_LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_LineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jC_LineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JF_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Actualizar;
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_Insertar;
    private javax.swing.JButton jB_Limpiar;
    private javax.swing.JButton jB_MostrarTodos;
    private javax.swing.JComboBox<String> jC_Linea;
    private javax.swing.JLabel jLbl_Codigo;
    private javax.swing.JLabel jLbl_Descripcion;
    private javax.swing.JLabel jLbl_Linea;
    private javax.swing.JLabel jLbl_Marca;
    private javax.swing.JLabel jLbl_Stock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_Productos;
    private javax.swing.JTextField jTxt_Codigo;
    private javax.swing.JTextField jTxt_Descripcion;
    private javax.swing.JTextField jTxt_Marca;
    private javax.swing.JTextField jTxt_Stock;
    // End of variables declaration//GEN-END:variables
}
